"""
Seestar Lab — static catalog data for Messier and Caldwell objects.

Each entry: (popular_name, dso_type, constellation, ngc_ref)
  popular_name — empty string if no well-known nickname
  dso_type     — one of: galaxy, open_cluster, globular_cluster,
                          planetary_nebula, emission_nebula, reflection_nebula,
                          supernova_remnant, dark_nebula, star_cloud,
                          asterism, double_star
  constellation — IAU constellation name
  ngc_ref      — primary NGC/IC/other catalogue reference (empty string if none)
"""

# ── Messier catalogue (M1–M110) ───────────────────────────────────────────────

MESSIER: dict[int, tuple[str, str, str, str]] = {
    1:   ("Crab Nebula",         "supernova_remnant",  "Taurus",              "NGC 1952"),
    2:   ("",                    "globular_cluster",   "Aquarius",            "NGC 7089"),
    3:   ("",                    "globular_cluster",   "Canes Venatici",      "NGC 5272"),
    4:   ("",                    "globular_cluster",   "Scorpius",            "NGC 6121"),
    5:   ("",                    "globular_cluster",   "Serpens",             "NGC 5904"),
    6:   ("Butterfly Cluster",   "open_cluster",       "Scorpius",            "NGC 6405"),
    7:   ("Ptolemy Cluster",     "open_cluster",       "Scorpius",            "NGC 6475"),
    8:   ("Lagoon Nebula",       "emission_nebula",    "Sagittarius",         "NGC 6523"),
    9:   ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6333"),
    10:  ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6254"),
    11:  ("Wild Duck Cluster",   "open_cluster",       "Scutum",              "NGC 6705"),
    12:  ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6218"),
    13:  ("Hercules Cluster",    "globular_cluster",   "Hercules",            "NGC 6205"),
    14:  ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6402"),
    15:  ("",                    "globular_cluster",   "Pegasus",             "NGC 7078"),
    16:  ("Eagle Nebula",        "emission_nebula",    "Serpens",             "NGC 6611"),
    17:  ("Omega Nebula",        "emission_nebula",    "Sagittarius",         "NGC 6618"),
    18:  ("",                    "open_cluster",       "Sagittarius",         "NGC 6613"),
    19:  ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6273"),
    20:  ("Trifid Nebula",       "emission_nebula",    "Sagittarius",         "NGC 6514"),
    21:  ("",                    "open_cluster",       "Sagittarius",         "NGC 6531"),
    22:  ("Sagittarius Cluster", "globular_cluster",   "Sagittarius",         "NGC 6656"),
    23:  ("",                    "open_cluster",       "Sagittarius",         "NGC 6494"),
    24:  ("Sagittarius Star Cloud", "star_cloud",      "Sagittarius",         ""),
    25:  ("",                    "open_cluster",       "Sagittarius",         "IC 4725"),
    26:  ("",                    "open_cluster",       "Scutum",              "NGC 6694"),
    27:  ("Dumbbell Nebula",     "planetary_nebula",   "Vulpecula",           "NGC 6853"),
    28:  ("",                    "globular_cluster",   "Sagittarius",         "NGC 6626"),
    29:  ("",                    "open_cluster",       "Cygnus",              "NGC 6913"),
    30:  ("",                    "globular_cluster",   "Capricornus",         "NGC 7099"),
    31:  ("Andromeda Galaxy",    "galaxy",             "Andromeda",           "NGC 224"),
    32:  ("",                    "galaxy",             "Andromeda",           "NGC 221"),
    33:  ("Triangulum Galaxy",   "galaxy",             "Triangulum",          "NGC 598"),
    34:  ("",                    "open_cluster",       "Perseus",             "NGC 1039"),
    35:  ("",                    "open_cluster",       "Gemini",              "NGC 2168"),
    36:  ("",                    "open_cluster",       "Auriga",              "NGC 1960"),
    37:  ("",                    "open_cluster",       "Auriga",              "NGC 2099"),
    38:  ("",                    "open_cluster",       "Auriga",              "NGC 1912"),
    39:  ("",                    "open_cluster",       "Cygnus",              "NGC 7092"),
    40:  ("Winnecke 4",          "double_star",        "Ursa Major",          ""),
    41:  ("",                    "open_cluster",       "Canis Major",         "NGC 2287"),
    42:  ("Orion Nebula",        "emission_nebula",    "Orion",               "NGC 1976"),
    43:  ("De Mairan's Nebula",  "emission_nebula",    "Orion",               "NGC 1982"),
    44:  ("Beehive Cluster",     "open_cluster",       "Cancer",              "NGC 2632"),
    45:  ("Pleiades",            "open_cluster",       "Taurus",              "Mel 22"),
    46:  ("",                    "open_cluster",       "Puppis",              "NGC 2437"),
    47:  ("",                    "open_cluster",       "Puppis",              "NGC 2422"),
    48:  ("",                    "open_cluster",       "Hydra",               "NGC 2548"),
    49:  ("",                    "galaxy",             "Virgo",               "NGC 4472"),
    50:  ("",                    "open_cluster",       "Monoceros",           "NGC 2323"),
    51:  ("Whirlpool Galaxy",    "galaxy",             "Canes Venatici",      "NGC 5194"),
    52:  ("",                    "open_cluster",       "Cassiopeia",          "NGC 7654"),
    53:  ("",                    "globular_cluster",   "Coma Berenices",      "NGC 5024"),
    54:  ("",                    "globular_cluster",   "Sagittarius",         "NGC 6715"),
    55:  ("",                    "globular_cluster",   "Sagittarius",         "NGC 6809"),
    56:  ("",                    "globular_cluster",   "Lyra",                "NGC 6779"),
    57:  ("Ring Nebula",         "planetary_nebula",   "Lyra",                "NGC 6720"),
    58:  ("",                    "galaxy",             "Virgo",               "NGC 4579"),
    59:  ("",                    "galaxy",             "Virgo",               "NGC 4621"),
    60:  ("",                    "galaxy",             "Virgo",               "NGC 4649"),
    61:  ("",                    "galaxy",             "Virgo",               "NGC 4303"),
    62:  ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6266"),
    63:  ("Sunflower Galaxy",    "galaxy",             "Canes Venatici",      "NGC 5055"),
    64:  ("Black Eye Galaxy",    "galaxy",             "Coma Berenices",      "NGC 4826"),
    65:  ("",                    "galaxy",             "Leo",                 "NGC 3623"),
    66:  ("",                    "galaxy",             "Leo",                 "NGC 3627"),
    67:  ("",                    "open_cluster",       "Cancer",              "NGC 2682"),
    68:  ("",                    "globular_cluster",   "Hydra",               "NGC 4590"),
    69:  ("",                    "globular_cluster",   "Sagittarius",         "NGC 6637"),
    70:  ("",                    "globular_cluster",   "Sagittarius",         "NGC 6681"),
    71:  ("",                    "globular_cluster",   "Sagitta",             "NGC 6838"),
    72:  ("",                    "globular_cluster",   "Aquarius",            "NGC 6981"),
    73:  ("",                    "asterism",           "Aquarius",            "NGC 6994"),
    74:  ("Phantom Galaxy",      "galaxy",             "Pisces",              "NGC 628"),
    75:  ("",                    "globular_cluster",   "Sagittarius",         "NGC 6864"),
    76:  ("Little Dumbbell",     "planetary_nebula",   "Perseus",             "NGC 650"),
    77:  ("Cetus A",             "galaxy",             "Cetus",               "NGC 1068"),
    78:  ("",                    "reflection_nebula",  "Orion",               "NGC 2068"),
    79:  ("",                    "globular_cluster",   "Lepus",               "NGC 1904"),
    80:  ("",                    "globular_cluster",   "Scorpius",            "NGC 6093"),
    81:  ("Bode's Galaxy",       "galaxy",             "Ursa Major",          "NGC 3031"),
    82:  ("Cigar Galaxy",        "galaxy",             "Ursa Major",          "NGC 3034"),
    83:  ("Southern Pinwheel",   "galaxy",             "Hydra",               "NGC 5236"),
    84:  ("",                    "galaxy",             "Virgo",               "NGC 4374"),
    85:  ("",                    "galaxy",             "Coma Berenices",      "NGC 4382"),
    86:  ("",                    "galaxy",             "Virgo",               "NGC 4406"),
    87:  ("Virgo A",             "galaxy",             "Virgo",               "NGC 4486"),
    88:  ("",                    "galaxy",             "Coma Berenices",      "NGC 4501"),
    89:  ("",                    "galaxy",             "Virgo",               "NGC 4552"),
    90:  ("",                    "galaxy",             "Virgo",               "NGC 4569"),
    91:  ("",                    "galaxy",             "Coma Berenices",      "NGC 4548"),
    92:  ("",                    "globular_cluster",   "Hercules",            "NGC 6341"),
    93:  ("",                    "open_cluster",       "Puppis",              "NGC 2447"),
    94:  ("Croc's Eye Galaxy",   "galaxy",             "Canes Venatici",      "NGC 4736"),
    95:  ("",                    "galaxy",             "Leo",                 "NGC 3351"),
    96:  ("",                    "galaxy",             "Leo",                 "NGC 3368"),
    97:  ("Owl Nebula",          "planetary_nebula",   "Ursa Major",          "NGC 3587"),
    98:  ("",                    "galaxy",             "Coma Berenices",      "NGC 4192"),
    99:  ("",                    "galaxy",             "Coma Berenices",      "NGC 4254"),
    100: ("",                    "galaxy",             "Coma Berenices",      "NGC 4321"),
    101: ("Pinwheel Galaxy",     "galaxy",             "Ursa Major",          "NGC 5457"),
    102: ("Spindle Galaxy",      "galaxy",             "Draco",               "NGC 5866"),
    103: ("",                    "open_cluster",       "Cassiopeia",          "NGC 581"),
    104: ("Sombrero Galaxy",     "galaxy",             "Virgo",               "NGC 4594"),
    105: ("",                    "galaxy",             "Leo",                 "NGC 3379"),
    106: ("",                    "galaxy",             "Canes Venatici",      "NGC 4258"),
    107: ("",                    "globular_cluster",   "Ophiuchus",           "NGC 6171"),
    108: ("",                    "galaxy",             "Ursa Major",          "NGC 3556"),
    109: ("",                    "galaxy",             "Ursa Major",          "NGC 3992"),
    110: ("",                    "galaxy",             "Andromeda",           "NGC 205"),
}

# ── Caldwell catalogue (C1–C109) ──────────────────────────────────────────────

CALDWELL: dict[int, tuple[str, str, str, str]] = {
    1:   ("",                       "open_cluster",      "Cepheus",            "NGC 188"),
    2:   ("Bow-Tie Nebula",         "planetary_nebula",  "Cepheus",            "NGC 40"),
    3:   ("",                       "galaxy",            "Draco",              "NGC 4236"),
    4:   ("Iris Nebula",            "reflection_nebula", "Cepheus",            "NGC 7023"),
    5:   ("",                       "galaxy",            "Camelopardalis",     "IC 342"),
    6:   ("Cat's Eye Nebula",       "planetary_nebula",  "Draco",              "NGC 6543"),
    7:   ("",                       "galaxy",            "Camelopardalis",     "NGC 2403"),
    8:   ("",                       "open_cluster",      "Cassiopeia",         "NGC 559"),
    9:   ("Cave Nebula",            "emission_nebula",   "Cepheus",            "Sh2-155"),
    10:  ("",                       "open_cluster",      "Cassiopeia",         "NGC 663"),
    11:  ("Bubble Nebula",          "emission_nebula",   "Cassiopeia",         "NGC 7635"),
    12:  ("Fireworks Galaxy",       "galaxy",            "Cepheus",            "NGC 6946"),
    13:  ("Owl Cluster",            "open_cluster",      "Cassiopeia",         "NGC 457"),
    14:  ("Double Cluster",         "open_cluster",      "Perseus",            "NGC 869/884"),
    15:  ("Blinking Planetary",     "planetary_nebula",  "Cygnus",             "NGC 6826"),
    16:  ("",                       "open_cluster",      "Lacerta",            "NGC 7243"),
    17:  ("",                       "galaxy",            "Cassiopeia",         "NGC 147"),
    18:  ("",                       "galaxy",            "Cassiopeia",         "NGC 185"),
    19:  ("Cocoon Nebula",          "emission_nebula",   "Cygnus",             "IC 5146"),
    20:  ("North America Nebula",   "emission_nebula",   "Cygnus",             "NGC 7000"),
    21:  ("",                       "galaxy",            "Canes Venatici",     "NGC 4449"),
    22:  ("Blue Snowball",          "planetary_nebula",  "Andromeda",          "NGC 7662"),
    23:  ("Silver Sliver",          "galaxy",            "Andromeda",          "NGC 891"),
    24:  ("Perseus A",              "galaxy",            "Perseus",            "NGC 1275"),
    25:  ("Intergalactic Wanderer", "globular_cluster",  "Lynx",               "NGC 2419"),
    26:  ("Silver Needle",          "galaxy",            "Canes Venatici",     "NGC 4244"),
    27:  ("Crescent Nebula",        "emission_nebula",   "Cygnus",             "NGC 6888"),
    28:  ("",                       "open_cluster",      "Andromeda",          "NGC 752"),
    29:  ("",                       "galaxy",            "Canes Venatici",     "NGC 5005"),
    30:  ("",                       "galaxy",            "Pegasus",            "NGC 7331"),
    31:  ("Flaming Star Nebula",    "emission_nebula",   "Auriga",             "IC 405"),
    32:  ("Whale Galaxy",           "galaxy",            "Canes Venatici",     "NGC 4631"),
    33:  ("East Veil Nebula",       "supernova_remnant", "Cygnus",             "NGC 6992"),
    34:  ("West Veil Nebula",       "supernova_remnant", "Cygnus",             "NGC 6960"),
    35:  ("",                       "galaxy",            "Coma Berenices",     "NGC 4889"),
    36:  ("",                       "galaxy",            "Coma Berenices",     "NGC 4559"),
    37:  ("",                       "open_cluster",      "Vulpecula",          "NGC 6885"),
    38:  ("Needle Galaxy",          "galaxy",            "Coma Berenices",     "NGC 4565"),
    39:  ("Eskimo Nebula",          "planetary_nebula",  "Gemini",             "NGC 2392"),
    40:  ("",                       "galaxy",            "Leo",                "NGC 3626"),
    41:  ("Hyades",                 "open_cluster",      "Taurus",             "Mel 25"),
    42:  ("",                       "globular_cluster",  "Delphinus",          "NGC 7006"),
    43:  ("",                       "galaxy",            "Pegasus",            "NGC 7814"),
    44:  ("",                       "galaxy",            "Pegasus",            "NGC 7479"),
    45:  ("",                       "galaxy",            "Bootes",             "NGC 5248"),
    46:  ("Hubble's Variable Neb.", "reflection_nebula", "Monoceros",          "NGC 2261"),
    47:  ("",                       "globular_cluster",  "Delphinus",          "NGC 6934"),
    48:  ("",                       "galaxy",            "Cancer",             "NGC 2775"),
    49:  ("Rosette Nebula",         "emission_nebula",   "Monoceros",          "NGC 2237"),
    50:  ("",                       "open_cluster",      "Monoceros",          "NGC 2244"),
    51:  ("",                       "galaxy",            "Cetus",              "IC 1613"),
    52:  ("",                       "galaxy",            "Virgo",              "NGC 4697"),
    53:  ("Spindle Galaxy",         "galaxy",            "Sextans",            "NGC 3115"),
    54:  ("",                       "open_cluster",      "Monoceros",          "NGC 2506"),
    55:  ("Saturn Nebula",          "planetary_nebula",  "Aquarius",           "NGC 7009"),
    56:  ("Skull Nebula",           "planetary_nebula",  "Cetus",              "NGC 246"),
    57:  ("Barnard's Galaxy",       "galaxy",            "Sagittarius",        "NGC 6822"),
    58:  ("",                       "open_cluster",      "Canis Major",        "NGC 2360"),
    59:  ("Ghost of Jupiter",       "planetary_nebula",  "Hydra",              "NGC 3242"),
    60:  ("Antennae Galaxies",      "galaxy",            "Corvus",             "NGC 4038"),
    61:  ("Antennae Galaxies",      "galaxy",            "Corvus",             "NGC 4039"),
    62:  ("",                       "galaxy",            "Cetus",              "NGC 247"),
    63:  ("Helix Nebula",           "planetary_nebula",  "Aquarius",           "NGC 7293"),
    64:  ("Tau CMa Cluster",        "open_cluster",      "Canis Major",        "NGC 2362"),
    65:  ("Sculptor Galaxy",        "galaxy",            "Sculptor",           "NGC 253"),
    66:  ("",                       "globular_cluster",  "Hydra",              "NGC 5694"),
    67:  ("",                       "galaxy",            "Fornax",             "NGC 1097"),
    68:  ("",                       "emission_nebula",   "Corona Australis",   "NGC 6729"),
    69:  ("Bug Nebula",             "planetary_nebula",  "Scorpius",           "NGC 6302"),
    70:  ("",                       "galaxy",            "Sculptor",           "NGC 300"),
    71:  ("",                       "open_cluster",      "Puppis",             "NGC 2477"),
    72:  ("",                       "galaxy",            "Sculptor",           "NGC 55"),
    73:  ("",                       "globular_cluster",  "Columba",            "NGC 1851"),
    74:  ("Eight-Burst Nebula",     "planetary_nebula",  "Vela",               "NGC 3132"),
    75:  ("",                       "open_cluster",      "Scorpius",           "NGC 6124"),
    76:  ("",                       "open_cluster",      "Scorpius",           "NGC 6231"),
    77:  ("Centaurus A",            "galaxy",            "Centaurus",          "NGC 5128"),
    78:  ("",                       "globular_cluster",  "Corona Australis",   "NGC 6541"),
    79:  ("",                       "globular_cluster",  "Vela",               "NGC 3201"),
    80:  ("Omega Centauri",         "globular_cluster",  "Centaurus",          "NGC 5139"),
    81:  ("",                       "globular_cluster",  "Ara",                "NGC 6352"),
    82:  ("",                       "open_cluster",      "Ara",                "NGC 6193"),
    83:  ("",                       "galaxy",            "Centaurus",          "NGC 4945"),
    84:  ("",                       "globular_cluster",  "Centaurus",          "NGC 5286"),
    85:  ("",                       "open_cluster",      "Vela",               "IC 2391"),
    86:  ("",                       "globular_cluster",  "Ara",                "NGC 6397"),
    87:  ("",                       "globular_cluster",  "Horologium",         "NGC 1261"),
    88:  ("",                       "open_cluster",      "Circinus",           "NGC 5823"),
    89:  ("",                       "open_cluster",      "Norma",              "NGC 6087"),
    90:  ("",                       "planetary_nebula",  "Carina",             "NGC 2867"),
    91:  ("Wishing Well Cluster",   "open_cluster",      "Carina",             "NGC 3532"),
    92:  ("Eta Carinae Nebula",     "emission_nebula",   "Carina",             "NGC 3372"),
    93:  ("",                       "globular_cluster",  "Pavo",               "NGC 6752"),
    94:  ("Jewel Box",              "open_cluster",      "Crux",               "NGC 4755"),
    95:  ("",                       "open_cluster",      "Triangulum Australe","NGC 6025"),
    96:  ("",                       "open_cluster",      "Carina",             "NGC 2516"),
    97:  ("Pearl Cluster",          "open_cluster",      "Centaurus",          "NGC 3766"),
    98:  ("",                       "open_cluster",      "Crux",               "NGC 4609"),
    99:  ("Coalsack",               "dark_nebula",       "Crux",               ""),
    100: ("Lambda Cen Nebula",      "emission_nebula",   "Centaurus",          "IC 2944"),
    101: ("",                       "galaxy",            "Pavo",               "NGC 6744"),
    102: ("Tarantula Nebula",       "emission_nebula",   "Dorado",             "NGC 2070"),
    103: ("",                       "globular_cluster",  "Tucana",             "NGC 362"),
    104: ("",                       "globular_cluster",  "Fornax",             "NGC 1049"),
    105: ("Robin's Egg Nebula",     "planetary_nebula",  "Fornax",             "NGC 1360"),
    106: ("47 Tucanae",             "globular_cluster",  "Tucana",             "NGC 104"),
    107: ("",                       "globular_cluster",  "Apus",               "NGC 6101"),
    108: ("",                       "globular_cluster",  "Musca",              "NGC 4372"),
    109: ("",                       "planetary_nebula",  "Chamaeleon",         "NGC 3195"),
}

# ── DSO type display labels ────────────────────────────────────────────────────

DSO_TYPE_LABELS: dict[str, str] = {
    "galaxy":            "Galaxy",
    "open_cluster":      "Open Cluster",
    "globular_cluster":  "Globular Cluster",
    "planetary_nebula":  "Planetary Nebula",
    "emission_nebula":   "Emission Nebula",
    "reflection_nebula": "Reflection Nebula",
    "supernova_remnant": "Supernova Remnant",
    "dark_nebula":       "Dark Nebula",
    "star_cloud":        "Star Cloud",
    "asterism":          "Asterism",
    "double_star":       "Double Star",
}

# Coarse groups used for catalog page filter tabs
DSO_TYPE_GROUP: dict[str, str] = {
    "galaxy":            "galaxy",
    "open_cluster":      "cluster",
    "globular_cluster":  "cluster",
    "planetary_nebula":  "nebula",
    "emission_nebula":   "nebula",
    "reflection_nebula": "nebula",
    "supernova_remnant": "nebula",
    "dark_nebula":       "nebula",
    "star_cloud":        "other",
    "asterism":          "other",
    "double_star":       "other",
}


def messier_display_name(number: int) -> str:
    """Return 'M42' style label."""
    return f"M{number}"


def caldwell_display_name(number: int) -> str:
    """Return 'C63' style label."""
    return f"C{number}"
